# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180731_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='loyalty',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
