# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180801_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtgcryptouser',
            name='about',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mtgcryptouser',
            name='address1',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mtgcryptouser',
            name='address2',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mtgcryptouser',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mtgcryptouser',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mtgcryptouser',
            name='postal_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mtgcryptouser',
            name='province',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mtgcryptouser',
            name='timezone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mtgcryptouser',
            name='twitter',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
