# Generated by Django 2.0.7 on 2018-07-25 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=141)),
                ('mana_cost', models.CharField(max_length=40)),
                ('cmc', models.DecimalField(decimal_places=2, max_digits=9)),
                ('type', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=400)),
                ('power', models.DecimalField(decimal_places=1, max_digits=3)),
                ('toughness', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='MTGSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Length has to be 3', regex='^\\w{3}$')])),
                ('name', models.CharField(max_length=40)),
                ('release_date', models.CharField(max_length=10)),
            ],
        ),
    ]
