# Generated by Django 2.0.7 on 2018-07-25 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180725_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='artist',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='number',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='card',
            name='set',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.MTGSet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.SlugField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
