# Generated by Django 2.0.7 on 2018-07-26 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180725_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ForeignCardName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('multiverseid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ForeignLanguage',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='foreigncardname',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ForeignLanguage'),
        ),
    ]
