# Generated by Django 2.0.7 on 2018-07-26 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180726_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreigncardname',
            name='card',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.ForeignCardName'),
            preserve_default=False,
        ),
    ]
