# Generated by Django 2.0.7 on 2018-07-26 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_foreigncardname_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Card')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Color')),
            ],
        ),
    ]
