# Generated by Django 2.0.7 on 2018-07-27 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cardcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtgset',
            name='id',
        ),
        migrations.AlterField(
            model_name='mtgset',
            name='code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Length has to be 3', regex='^\\w{3}$')]),
        ),
    ]
