# Generated by Django 2.0.7 on 2018-07-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180727_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.IntegerField(choices=[(1, 'un'), (2, 'expansion'), (3, 'core'), (4, 'starter'), (5, 'box'), (6, 'reprint')], default=2),
        ),
    ]
