# Generated by Django 2.0.7 on 2018-07-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180727_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='layout',
            field=models.IntegerField(choices=[(1, 'normal'), (2, 'flip'), (3, 'split'), (4, 'aftermath'), (5, 'token'), (6, 'double-faced'), (7, 'leveler'), (8, 'phenomenon'), (9, 'meld'), (10, 'vanguard'), (11, 'plane'), (12, 'scheme')], default=1),
        ),
    ]
