# Generated by Django 2.0.7 on 2018-07-27 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLegality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legality', models.IntegerField(choices=[(1, 'banned'), (2, 'restricted')], default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Card')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Format')),
            ],
        ),
    ]
