# Generated by Django 2.0.7 on 2018-07-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cardlegality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foreigncardname',
            old_name='multiverseid',
            new_name='multiverse_id',
        ),
        migrations.AddField(
            model_name='card',
            name='multiverse_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
