# Generated by Django 2.0.7 on 2018-07-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180727_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='multiverse_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='foreigncardname',
            name='multiverse_id',
            field=models.PositiveIntegerField(),
        ),
    ]
