# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180727_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='set',
        ),
        migrations.AddField(
            model_name='card',
            name='mtgset',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.MTGSet'),
            preserve_default=False,
        ),
    ]
