# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180731_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.IntegerField(choices=[(1, 'common'), (2, 'uncommon'), (3, 'rare'), (4, 'mythic rare'), (5, 'basic land'), (6, 'special')], default=1),
        ),
    ]
