# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180731_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='amount',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
